coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 75%

# Excluded from coverage calculations (non-production code)
ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "include/net-net/vendor/**/*"
  - "vendor/**/*"
  - "build/**/*"
  - "CMakeFiles/**/*"
  - "src/main.cpp"
  - "src/daemon/Main.cpp"
  # - "**/*.h"  # If you don't want header coverage

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false