coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 70%

# Critical: Tell Codecov to ignore vendor files
ignore:
  - "include/net-net/vendor/**/*"
  - "vendor/**/*"
  - "tests/**/*"
  - "examples/**/*"
  - "build/**/*"
  - "CMakeFiles/**/*"
  - "src/main.cpp"
  - "src/daemon/Main.cpp"
  - "**/*.h"  # Optional: exclude headers if you don't want them counted

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false